default:
	scripts/build.sh && scripts/run-bg-mount.sh
build:
	scripts/build.sh
run-fg:
	scripts/run-fg.sh
run-bg:
	scripts/run-bg.sh
run-bg-mount:
	scripts/run-bg-mount.sh
shell:
	scripts/shell.sh
start:
	scripts/start.sh
stop:
	scripts/stop.sh
destroy:
	scripts/destroy.sh
